const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('api', {
  getAppVersion:      ()           => ipcRenderer.invoke('get-app-version'),
  getSystemInfo:      ()           => ipcRenderer.invoke('get-system-info'),
  isAdmin:            ()           => ipcRenderer.invoke('is-admin'),
  relaunchAdmin:      ()           => ipcRenderer.invoke('relaunch-admin'),
  getMetrics:         ()           => ipcRenderer.invoke('get-metrics'),
  minimize:           ()           => ipcRenderer.invoke('window-minimize'),
  maximize:           ()           => ipcRenderer.invoke('window-maximize'),
  close:              ()           => ipcRenderer.invoke('window-close'),
  loadSettings:       ()           => ipcRenderer.invoke('load-settings'),
  saveSettings:       (data)       => ipcRenderer.invoke('save-settings', data),
  runTweak:           (id, action) => ipcRenderer.invoke('run-tweak', { id, action }),
  createRestorePoint: (desc)       => ipcRenderer.invoke('create-restore-point', desc),
  listRestorePoints:  ()           => ipcRenderer.invoke('list-restore-points'),
  restoreToPoint:     (seq)        => ipcRenderer.invoke('restore-to-point', seq),
  scanUwpApps:        ()           => ipcRenderer.invoke('scan-uwp-apps'),
  removeUwpApps:      (pkgs)       => ipcRenderer.invoke('remove-uwp-apps', pkgs),
  disableServices:    (svcs)       => ipcRenderer.invoke('disable-services', svcs),
  disableScheduledTasks: (tasks)   => ipcRenderer.invoke('disable-scheduled-tasks', tasks),
  getUnusedDevices:   ()           => ipcRenderer.invoke('get-unused-devices'),
  removeDevices:      (ids)        => ipcRenderer.invoke('remove-devices', ids),
  fivemClearCache:    ()           => ipcRenderer.invoke('fivem-clear-cache'),
  fivemReadSettings:  (manualPath) => ipcRenderer.invoke('fivem-read-settings', manualPath),
  fivemWriteSettings: (changes, manualPath) => ipcRenderer.invoke('fivem-write-settings', changes, manualPath),
  cleanSystem:        (paths)      => ipcRenderer.invoke('clean-system', paths),
  runAutoOpti:        (si)         => ipcRenderer.invoke('run-auto-opti', si),
  applyGameTweak:     (id, action) => ipcRenderer.invoke('apply-game-tweak', { gameId: id, action }),
  getProcesses:       ()           => ipcRenderer.invoke('get-processes'),
  killProcess:        (pid)        => ipcRenderer.invoke('kill-process', pid),
  gameBoostApply:     ()           => ipcRenderer.invoke('game-boost-apply'),
  gameBoostRestore:   ()           => ipcRenderer.invoke('game-boost-restore'),
  openPulseWindow:    ()           => ipcRenderer.invoke('open-pulse-window'),
  closePulseWindow:   ()           => ipcRenderer.invoke('close-pulse-window'),
  openFivemSettings:    ()           => ipcRenderer.invoke('open-fivem-settings'),
  closeFivemSettings:   ()           => ipcRenderer.invoke('close-fivem-settings'),
  analyticsPageVisit:   (page)       => ipcRenderer.invoke('analytics-page-visit', page),
  analyticsTweakApplied: ()          => ipcRenderer.invoke('analytics-tweak-applied'),
  pulseStart:         (opts)       => ipcRenderer.invoke('pulse-start', opts),
  pulseStop:          ()           => ipcRenderer.invoke('pulse-stop'),
  pulseGetPresets:    ()           => ipcRenderer.invoke('pulse-get-presets'),
  pulseDetectGame:    ()           => ipcRenderer.invoke('pulse-detect-game'),
  onPulseTick:        (cb)         => ipcRenderer.on('pulse-tick', (_, d) => cb(d)),
  getStartupItems:    ()           => ipcRenderer.invoke('get-startup-items'),
  toggleStartupItem:  (item)       => ipcRenderer.invoke('toggle-startup-item', item),
  runPingTests:       ()           => ipcRenderer.invoke('run-ping-tests'),
  detectGames:        ()           => ipcRenderer.invoke('detect-games'),
  startGameWatcher:   ()           => ipcRenderer.invoke('start-game-watcher'),
  stopGameWatcher:    ()           => ipcRenderer.invoke('stop-game-watcher'),
  getGameWatcherStatus: ()         => ipcRenderer.invoke('get-game-watcher-status'),
  getChangelog:       ()           => ipcRenderer.invoke('get-changelog'),
  addChangelogEntry:  (entry)      => ipcRenderer.invoke('add-changelog-entry', entry),
  clearChangelog:     ()           => ipcRenderer.invoke('clear-changelog'),
  scheduleTweak:      (opts)       => ipcRenderer.invoke('schedule-tweak', opts),
  listScheduledTweaks: ()          => ipcRenderer.invoke('list-scheduled-tweaks'),
  deleteScheduledTweak: (name)     => ipcRenderer.invoke('delete-scheduled-tweak', name),
  getTempSize:        ()           => ipcRenderer.invoke('get-temp-size'),
  getHealthScore:     (settings)   => ipcRenderer.invoke('get-health-score', settings),
  checkUpdate:        ()           => ipcRenderer.invoke('check-update'),
  downloadUpdate:     ()           => ipcRenderer.invoke('download-update'),
  installUpdate:      ()           => ipcRenderer.invoke('install-update'),
  getWhatsNew:        ()           => ipcRenderer.invoke('get-whats-new'),
  runAppOptimizer:    (id, action) => ipcRenderer.invoke('run-app-optimizer', { id, action }),
  onWindowsHealthProgress: (cb) => ipcRenderer.on('windows-health-progress', (_, d) => cb(d)),
  onSpecProgress:     (cb) => ipcRenderer.on('spec-progress',     (_, d) => cb(d)),
  onLog:              (cb) => ipcRenderer.on('log',               (_, d) => cb(d)),
  onAutoOptiProgress: (cb) => ipcRenderer.on('auto-opti-progress',(_, d) => cb(d)),
  onDebloatProgress:  (cb) => ipcRenderer.on('debloat-progress',  (_, d) => cb(d)),
  onPingResult:       (cb) => ipcRenderer.on('ping-result',       (_, d) => cb(d)),
  onGameWatcherEvent: (cb) => ipcRenderer.on('game-watcher-event',(_, d) => cb(d)),
  onUpdateAvailable:  (cb) => ipcRenderer.on('update-available',  (_, d) => cb(d)),
  onUpdateProgress:   (cb) => ipcRenderer.on('update-progress',   (_, d) => cb(d)),
  onUpdateDownloaded: (cb) => ipcRenderer.on('update-downloaded', (_, d) => cb(d)),
  openExternal:       (url)        => ipcRenderer.invoke('open-external', url),
  discordSetPage:         (page)         => ipcRenderer.invoke('discord-set-page', page),
  discordSetTweaks:       (count)        => ipcRenderer.invoke('discord-set-tweaks', count),
  discordSetAppliedCount: (count)        => ipcRenderer.invoke('discord-set-applied-count', count),
  discordSetFiveM:        (has)          => ipcRenderer.invoke('discord-set-fivem', has),
  discordSetPulseGame:    (name)         => ipcRenderer.invoke('discord-set-pulse-game', name),
  discordSetActiveGame:   (name)         => ipcRenderer.invoke('discord-set-active-game', name),
  onDiscordReady:     (cb)         => ipcRenderer.on('discord-rpc-ready', () => cb()),
  submitBugReport:    (data)       => ipcRenderer.invoke('submit-bug-report', data),
  runFix:             (id)         => ipcRenderer.invoke('run-fix', id),
  runWindowsHealth:   ()           => ipcRenderer.invoke('run-windows-health'),
  runPreflightScan:   ()           => ipcRenderer.invoke('run-preflight-scan'),
  onTrayPulseChanged: (cb)         => ipcRenderer.on('tray-pulse-changed', (_, d) => cb(d)),
})
